### ISSUE TITLE
Need help with nav and markbot error

### ISSUE THREAD

**Issue by char1129** [char1129/kraken-good-accessibility#1]
Hello @hellachella @jessjodoin
<img width="518" alt="Screen Shot 2020-09-19 at 11 58 24 PM" src="https://user-images.githubusercontent.com/55107755/93693947-64d65400-fad4-11ea-889a-44bc53553523.png">

I can't seem to resolve the above markbot error and even though the container is flex, I cannot get the nav to float above on a different z-index and move it to the right.

Help~!  (Please 😊)

**Comment by JessJodoin** [comment]
I think the has to do with the navigation not focusing correctly, so add this:

`nav a:focus {
  outline: .2rem solid #000;
  outline-offset: .1rem;
}`

**Comment by char1129** [comment]
> nav a:focus { outline: .2rem solid #000; outline-offset: .1rem; }

Thanks for the reply @JessJodoin 
I'm still getting the same error. I'm guessing its a class I need to add in the html or some css I need to redirect that doesn't seem to be finding their associated html.
I'll let you know if I figure out a fix.

**Comment by JessJodoin** [comment]
Just out of curiosity, how much did you add to the css file? In mine, the only thing I added was the focus state cause everything else should be already done for you.

**Comment by char1129** [comment]
A couple things... I found the html to too div happy on first glance, and did end up adding a few back when I started troubleshooting. Perhaps I need to refork the assignment and start again. :S

**Comment by JessJodoin** [comment]
Want to DM on slack and work through it? (totally cool if you don't want to, or you're busy 😃 )

**Comment by char1129** [comment]
@JessJodoin Hi Jess! Sorry I didn't see this part of the reply until late yesterday; I've been focusing on a big assignment for another class. I'll work on this issue tomorrow and let you know how it goes 😊

**Comment by JessJodoin** [comment]
Okay! So I've made a list of stuff, hopefully this will fix everything 😄 

**INDEX.HTML**

Line 18/42 - change `div` to `header`

Line 19/22 - change `div` to `hgroup`

Line 44 - add `role=“main”` to the `div`

Line 62 - add `aria-details=“”` and # an id (target id from line 63)

Line 63 - add an `id=""`


**MAIN.CSS**

Line 26 (put inside header {} )
- `background-color: #1e7c74;`

Line 46 (inside article div {} )
- remove `display: contents;`

Line 98 (.current)
- don’t have to include a .current, Markbot isn’t looking for it

Line 103 (after the nav a stuff)
- add
```
nav a:focus {
  outline: .2rem solid #000;
  outline-offset: .1rem;
}
```

Line 135 (article div)
- un-comment it out

Line 157 (article footer)
- un-comment out `background-color` and `background-image`

Line 164 (footer)
- remove `font-weight`
- add `background-color: #1e7c74;`
- remove everything after closing brace

Let me know if there are any other issues 👍

**Comment by char1129** [comment]
> Okay! So I've made a list of stuff, hopefully this will fix everything 😄
> 
> **INDEX.HTML**
> 
> Line 18/42 - change `div` to `header`
> 
> Line 19/22 - change `div` to `hgroup`
> 
> Line 44 - add `role=“main”` to the `div`
> 
> Line 62 - add `aria-details=“”` and # an id (target id from line 63)
> 
> Line 63 - add an `id=""`
> 
> **MAIN.CSS**
> 
> Line 26 (put inside header {} )
> 
> * `background-color: #1e7c74;`
> 
> Line 46 (inside article div {} )
> 
> * remove `display: contents;`
> 
> Line 98 (.current)
> 
> * don’t have to include a .current, Markbot isn’t looking for it
> 
> Line 103 (after the nav a stuff)
> 
> * add
> 
> ```
> nav a:focus {
>   outline: .2rem solid #000;
>   outline-offset: .1rem;
> }
> ```
> 
> Line 135 (article div)
> 
> * un-comment it out
> 
> Line 157 (article footer)
> 
> * un-comment out `background-color` and `background-image`
> 
> Line 164 (footer)
> 
> * remove `font-weight`
> * add `background-color: #1e7c74;`
> * remove everything after closing brace
> 
> Let me know if there are any other issues 👍

HOLY MOLY! Let me try this out right now that I've freed myself from the claws of other classes. 😊

**Comment by char1129** [comment]
@JessJodoin Thank you so much for all the suggestions. I've implemented them, the background was fixed - I unmuted a background colour I had and added the other one you suggested.
The error about the Nav Focus and the Nav Hover are still persisting. See attached screen capture. Also my markbot for this one file won't complete the check. The gear is constantly rotating. I have to close it and relaunch it just for it to re-evaluate the file.
<img width="793" alt="Screen Shot 2020-09-25 at 11 18 58 AM" src="https://user-images.githubusercontent.com/55107755/94284965-1afccc00-ff21-11ea-8246-5eac21a33b7b.png">

**Comment by char1129** [comment]
@JessJodoin Awesome! 
All issues are resolved! Thank you so much! 
Markbot is just having an issue verifying with the screenshot and it's clog won't stop rotating. I think there is something wrong with the image (It's missing a footer).
I'm going to send Chelle a slack and screencapture with the completion. Hopefully she can mark it off as complete there 😊

Thanks a million again! 
 
<img width="1107" alt="Screen Shot 2020-09-25 at 11 27 11 AM" src="https://user-images.githubusercontent.com/55107755/94285780-23a1d200-ff22-11ea-95a9-f8ea4a574e35.png">
